# Generated by Django 5.2.4 on 2025-07-28 10:43

import common.utils.file_path_in_bucket as file_path_in_bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AddField(
            model_name='file',
            name='uploaded_file',
            field=models.FileField(default=10, upload_to=file_path_in_bucket.create_file_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FileVersion',
        ),
    ]
