# Generated by Django 5.2.4 on 2025-07-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_rename_name_file_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
