# Generated by Django 5.2.4 on 2025-07-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(default='main', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
